### ISSUE TITLE
Using the newer Raspbian Stretch

### ISSUE THREAD

**Issue by johnshearing** [Robpol86/robpol86.com#14]
Hi @Robpol86 
Made an airgapped raspberry pi using qr-codes to cross the airgap.
[Open source make instructions with photos here.](https://github.com/johnshearing/PrivateKeyVault#privatekeyvault---make-instructions)

[Your instructions for installing LUKS are included in the documentation](https://github.com/johnshearing/PrivateKeyVault#setup-luks-full-disk-encryption)

I think it only works on Jessie and not on Stretch.
Is this true?
If so, would you consider an update?
If not, would you please tell me what I am doing wrong?
It matters because I think this device can help with mass-adoption of blockchain services which I imagine will make life better for all of us.
Thanks, John

**Comment by Robpol86** [comment]
Unfortunately I no longer maintain a Pi with LUKS so I won't be updating the page until I happen to work on a future project that needs it.
